curl http://localhost:3000/api/health

###

curl -N POST http://localhost:3000/api/openai/v1/chat/completions \
-H "Content-Type: application/json" \
-H "Authorization: Bearer sk-proj-1234567890" \
-d '{
  "model": "dev/dev-claude-3-7-sonnet",
  "stream": true,
#   "model": "dev/dev-gemini-1.5-pro",
  "messages": [
    {
      "role": "user",
      "content": "http event steam 如何在vscode中直观的观察？"
    }
  ]
}'

###

curl -N POST http://localhost:3000/api/hello \
-H "Content-Type: application/json" \
-H "Authorization: Bearer sk-proj-1234567890" \
-d '{
  "model": "dev/dev-claude-3-7-sonnet",
  "messages": [
    {
      "role": "user",
      "content": "gemma-3-27b有cloud模型吗？"
    }
  ]
}'
