
            
                    let bytes;
                    const base64 = "AGFzbQEAAAABSAtgAABgAX8AYAF/AX9gAn9/AGACf38Bf2ADf39/AGADf39/AX9gBH9/f38AYAR/f39/AX9gBX9/f39/AGAJf39/f39/f39/AAMmJQUCBAoBBAgEAwQEBQYDAQQJCQMFBAcDBAYACAgEBAEDBAIFBAEEBQFwAQ0NBQMBABEGCQF/AUGAgMAACwduBgZtZW1vcnkCAARzaWduAAMfX193YmluZGdlbl9hZGRfdG9fc3RhY2tfcG9pbnRlcgAhEV9fd2JpbmRnZW5fbWFsbG9jABcSX193YmluZGdlbl9yZWFsbG9jABsPX193YmluZGdlbl9mcmVlACIJEgEAQQELDAUgHQIPHhgJIyQcHwqAoQElqyoBJX8jAEGAAWsiAyQAIANBwAAQFCEDIAEgAkEGdGohJyAAKAIAIR8gACgCBCEgIAAoAgghIyAAKAIMISQgACgCECEhIAAoAhQhIiAAKAIYISUgACgCHCEmA0BBACECA0AgAiADaiABIAJqKAAAIg9BGHQgD0GA/gNxQQh0ciAPQQh2QYD+A3EgD0EYdnJyNgIAIAJBBGoiAkHAAEcNAAsgAygCPCEVIAMoAjghFiADKAI0IR0gAygCMCECIAMoAiwhFyADKAIoIRggAygCJCEZIAMoAiAhECADKAIcIRogAygCGCEbIAMoAhQhHCADKAIQIREgAygCDCEPIAMoAgghEiADKAIEIRMgAygCACEUIAMgIzYCYCADICQ2AmQgAyAlNgJoIAMgJjYCbCADICI2AnwgAyAhNgJ4IAMgIDYCdCADIB82AnAgA0HQAGoiCSADQeAAaiIKIANB8ABqIgsgE0GRid2JB2ogFEGY36iUBGoQESADKAJQIQQgAygCVCEFIAMoAlghBiADKAJcIQcgAyAiNgJsIAMgITYCaCADICA2AmQgAyAfNgJgIAMgBzYCfCADIAY2AnggAyAFNgJ0IAMgBDYCcCAJIAogCyAPQdvIqLIBayASQbGI/NEEaxARIAMoAlAhCCADKAJUIQwgAygCWCENIAMoAlwhDiADIAc2AmwgAyAGNgJoIAMgBTYCZCADIAQ2AmAgAyAONgJ8IAMgDTYCeCADIAw2AnQgAyAINgJwIAkgCiALIBxB8aPEzwVqIBFB24TbygNqEBEgAygCUCEEIAMoAlQhBSADKAJYIQYgAygCXCEHIAMgDjYCbCADIA02AmggAyAMNgJkIAMgCDYCYCADIAc2AnwgAyAGNgJ4IAMgBTYCdCADIAQ2AnAgCSAKIAsgGkGrwo6nBWsgG0Hc+oHuBmsQESADKAJQIQggAygCVCEMIAMoAlghDSADKAJcIQ4gAyAHNgJsIAMgBjYCaCADIAU2AmQgAyAENgJgIAMgDjYCfCADIA02AnggAyAMNgJ0IAMgCDYCcCAJIAogCyAZQYG2jZQBaiAQQeiq4b8CaxARIAMoAlAhBCADKAJUIQUgAygCWCEGIAMoAlwhByADIA42AmwgAyANNgJoIAMgDDYCZCADIAg2AmAgAyAHNgJ8IAMgBjYCeCADIAU2AnQgAyAENgJwIAkgCiALIBdBw/uxqAVqIBhBvovGoQJqEBEgAygCUCEIIAMoAlQhDCADKAJYIQ0gAygCXCEOIAMgBzYCbCADIAY2AmggAyAFNgJkIAMgBDYCYCADIA42AnwgAyANNgJ4IAMgDDYCdCADIAg2AnAgCSAKIAsgHUGCnIX5B2sgAkH0uvmVB2oQESADKAJQIQQgAygCVCEFIAMoAlghBiADKAJcIQcgAyAONgJsIAMgDTYCaCADIAw2AmQgAyAINgJgIAMgBzYCfCADIAY2AnggAyAFNgJ0IAMgBDYCcCAJIAogCyAVQYydkPMDayAWQdnyj6EGaxARIAMoAlAhCCADKAJUIQwgAygCWCENIAMoAlwhDiADIBQ2AlwgAyATNgJYIAMgEjYCVCADIA82AlAgAyAQNgJsIAMgGTYCaCADIBg2AmQgAyAXNgJgIAMgAjYCfCADIB02AnggAyAWNgJ0IAMgFTYCcCADQUBrIh4gCSARIAogCxAQIAMoAkAhEiADKAJEIRMgAygCSCEUIAMoAkwhDyADIAc2AmwgAyAGNgJoIAMgBTYCZCADIAQ2AmAgAyAONgJ8IAMgDTYCeCADIAw2AnQgAyAINgJwIAkgCiALIBRB+vCGggFrIA9Bv6yS2wFrEBEgAygCUCEEIAMoAlQhBSADKAJYIQYgAygCXCEHIAMgDjYCbCADIA02AmggAyAMNgJkIAMgCDYCYCADIAc2AnwgAyAGNgJ4IAMgBTYCdCADIAQ2AnAgCSAKIAsgEkHMw7KgAmogE0HGu4b+AGoQESADKAJQIQggAygCVCEMIAMoAlghDSADKAJcIQ4gAyARNgJcIAMgHDYCWCADIBs2AlQgAyAaNgJQIAMgAjYCbCADIB02AmggAyAWNgJkIAMgFTYCYCADIA82AnwgAyAUNgJ4IAMgEzYCdCADIBI2AnAgHiAJIBAgCiALEBAgAygCQCEaIAMoAkQhGyADKAJIIRwgAygCTCERIAMgBzYCbCADIAY2AmggAyAFNgJkIAMgBDYCYCADIA42AnwgAyANNgJ4IAMgDDYCdCADIAg2AnAgCSAKIAsgHEGqidLTBGogEUHv2KTvAmoQESADKAJQIQQgAygCVCEFIAMoAlghBiADKAJcIQcgAyAONgJsIAMgDTYCaCADIAw2AmQgAyAINgJgIAMgBzYCfCADIAY2AnggAyAFNgJ0IAMgBDYCcCAJIAogCyAaQdqR5rcHaiAbQdzTwuUFahARIAMoAlAhCCADKAJUIQwgAygCWCENIAMoAlwhDiADIBA2AlwgAyAZNgJYIAMgGDYCVCADIBc2AlAgAyAPNgJsIAMgFDYCaCADIBM2AmQgAyASNgJgIAMgETYCfCADIBw2AnggAyAbNgJ0IAMgGjYCcCAeIAkgAiAKIAsQECADKAJAIRcgAygCRCEYIAMoAkghGSADKAJMIRAgAyAHNgJsIAMgBjYCaCADIAU2AmQgAyAENgJgIAMgDjYCfCADIA02AnggAyAMNgJ0IAMgCDYCcCAJIAogCyAZQZPzuL4FayAQQa7dhr4GaxARIAMoAlAhBCADKAJUIQUgAygCWCEGIAMoAlwhByADIA42AmwgAyANNgJoIAMgDDYCZCADIAg2AmAgAyAHNgJ8IAMgBjYCeCADIAU2AnQgAyAENgJwIAkgCiALIBdBuYCahQRrIBhBuLDz/wRrEBEgAygCUCEIIAMoAlQhDCADKAJYIQ0gAygCXCEOIAMgAjYCXCADIB02AlggAyAWNgJUIAMgFTYCUCADIBE2AmwgAyAcNgJoIAMgGzYCZCADIBo2AmAgAyAQNgJ8IAMgGTYCeCADIBg2AnQgAyAXNgJwIB4gCSAPIAogCxAQIAMoAkAhFSADKAJEIRYgAygCSCEdIAMoAkwhAiADIAc2AmwgAyAGNgJoIAMgBTYCZCADIAQ2AmAgAyAONgJ8IAMgDTYCeCADIAw2AnQgAyAINgJwIAkgCiALIB1Bud3h0gJrIAJBjej/yANrEBEgAygCUCEEIAMoAlQhBSADKAJYIQYgAygCXCEHIAMgDjYCbCADIA02AmggAyAMNgJkIAMgCDYCYCADIAc2AnwgAyAGNgJ4IAMgBTYCdCADIAQ2AnAgCSAKIAsgFUHn0qShAWogFkHRxqk2ahARIAMoAlAhCCADKAJUIQwgAygCWCENIAMoAlwhDiADIA82AlwgAyAUNgJYIAMgEzYCVCADIBI2AlAgAyAQNgJsIAMgGTYCaCADIBg2AmQgAyAXNgJgIAMgAjYCfCADIB02AnggAyAWNgJ0IAMgFTYCcCAeIAkgESAKIAsQECADKAJAIRIgAygCRCETIAMoAkghFCADKAJMIQ8gAyAHNgJsIAMgBjYCaCADIAU2AmQgAyAENgJgIAMgDjYCfCADIA02AnggAyAMNgJ0IAMgCDYCcCAJIAogCyAUQbjC7PACaiAPQYWV3L0CahARIAMoAlAhBCADKAJUIQUgAygCWCEGIAMoAlwhByADIA42AmwgAyANNgJoIAMgDDYCZCADIAg2AmAgAyAHNgJ8IAMgBjYCeCADIAU2AnQgAyAENgJwIAkgCiALIBJBk5rgmQVqIBNB/Nux6QRqEBEgAygCUCEIIAMoAlQhDCADKAJYIQ0gAygCXCEOIAMgETYCXCADIBw2AlggAyAbNgJUIAMgGjYCUCADIAI2AmwgAyAdNgJoIAMgFjYCZCADIBU2AmAgAyAPNgJ8IAMgFDYCeCADIBM2AnQgAyASNgJwIB4gCSAQIAogCxAQIAMoAkAhGiADKAJEIRsgAygCSCEcIAMoAkwhESADIAc2AmwgAyAGNgJoIAMgBTYCZCADIAQ2AmAgAyAONgJ8IAMgDTYCeCADIAw2AnQgAyAINgJwIAkgCiALIBxBu5WoswdqIBFB1OapqAZqEBEgAygCUCEEIAMoAlQhBSADKAJYIQYgAygCXCEHIAMgDjYCbCADIA02AmggAyAMNgJkIAMgCDYCYCADIAc2AnwgAyAGNgJ4IAMgBTYCdCADIAQ2AnAgCSAKIAsgGkH7prfsBmsgG0HS7fTxB2sQESADKAJQIQggAygCVCEMIAMoAlghDSADKAJcIQ4gAyAQNgJcIAMgGTYCWCADIBg2AlQgAyAXNgJQIAMgDzYCbCADIBQ2AmggAyATNgJkIAMgEjYCYCADIBE2AnwgAyAcNgJ4IAMgGzYCdCADIBo2AnAgHiAJIAIgCiALEBAgAygCQCEXIAMoAkQhGCADKAJIIRkgAygCTCEQIAMgBzYCbCADIAY2AmggAyAFNgJkIAMgBDYCYCADIA42AnwgAyANNgJ4IAMgDDYCdCADIAg2AnAgCSAKIAsgGUG1s5a/BWsgEEHfroDqBWsQESADKAJQIQQgAygCVCEFIAMoAlghBiADKAJcIQcgAyAONgJsIAMgDTYCaCADIAw2AmQgAyAINgJgIAMgBzYCfCADIAY2AnggAyAFNgJ0IAMgBDYCcCAJIAogCyAXQd3czsQDayAYQZDp0e0DaxARIAMoAlAhCCADKAJUIQwgAygCWCENIAMoAlwhDiADIAI2AlwgAyAdNgJYIAMgFjYCVCADIBU2AlAgAyARNgJsIAMgHDYCaCADIBs2AmQgAyAaNgJgIAMgEDYCfCADIBk2AnggAyAYNgJ0IAMgFzYCcCAeIAkgDyAKIAsQECADKAJAIRUgAygCRCEWIAMoAkghHSADKAJMIQIgAyAHNgJsIAMgBjYCaCADIAU2AmQgAyAENgJgIAMgDjYCfCADIA02AnggAyAMNgJ0IAMgCDYCcCAJIAogCyAdQdzzm8sCayACQeevtPMCaxARIAMoAlAhBCADKAJUIQUgAygCWCEGIAMoAlwhByADIA42AmwgAyANNgJoIAMgDDYCZCADIAg2AmAgAyAHNgJ8IAMgBjYCeCADIAU2AnQgAyAENgJwIAkgCiALIBVB8MCqgwFqIBZB+5TH3wBrEBEgAygCUCEIIAMoAlQhDCADKAJYIQ0gAygCXCEOIAMgDzYCXCADIBQ2AlggAyATNgJUIAMgEjYCUCADIBA2AmwgAyAZNgJoIAMgGDYCZCADIBc2AmAgAyACNgJ8IAMgHTYCeCADIBY2AnQgAyAVNgJwIB4gCSARIAogCxAQIAMoAkAhEiADKAJEIRMgAygCSCEUIAMoAkwhDyADIAc2AmwgAyAGNgJoIAMgBTYCZCADIAQ2AmAgAyAONgJ8IAMgDTYCeCADIAw2AnQgAyAINgJwIAkgCiALIBRBiNjd8QFqIA9BloKTzQFqEBEgAygCUCEEIAMoAlQhBSADKAJYIQYgAygCXCEHIAMgDjYCbCADIA02AmggAyAMNgJkIAMgCDYCYCADIAc2AnwgAyAGNgJ4IAMgBTYCdCADIAQ2AnAgCSAKIAsgEkG1+cKlA2ogE0HM7qG6AmoQESADKAJQIQggAygCVCEMIAMoAlghDSADKAJcIQ4gAyARNgJcIAMgHDYCWCADIBs2AlQgAyAaNgJQIAMgAjYCbCADIB02AmggAyAWNgJkIAMgFTYCYCADIA82AnwgAyAUNgJ4IAMgEzYCdCADIBI2AnAgHiAJIBAgCiALEBAgAygCQCERIAMoAkQhGiADKAJIIRsgAygCTCEcIAMgBzYCbCADIAY2AmggAyAFNgJkIAMgBDYCYCADIA42AnwgAyANNgJ4IAMgDDYCdCADIAg2AnAgCSAKIAsgG0HK1OL2BGogHEGzmfDIA2oQESADKAJQIQQgAygCVCEFIAMoAlghBiADKAJcIQcgAyAONgJsIAMgDTYCaCADIAw2AmQgAyAINgJgIAMgBzYCfCADIAY2AnggAyAFNgJ0IAMgBDYCcCAJIAogCyARQfPfucEGaiAaQc+U89wFahARIAMoAlAhCCADKAJUIQwgAygCWCENIAMoAlwhDiADIBA2AlwgAyAZNgJYIAMgGDYCVCADIBc2AlAgAyAPNgJsIAMgFDYCaCADIBM2AmQgAyASNgJgIAMgHDYCfCADIBs2AnggAyAaNgJ0IAMgETYCcCAeIAkgAiAKIAsQECADKAJAIRAgAygCRCESIAMoAkghEyADKAJMIRQgAyAHNgJsIAMgBjYCaCADIAU2AmQgAyAENgJgIAMgDjYCfCADIA02AnggAyAMNgJ0IAMgCDYCcCAJIAogCyATQe/GlcUHaiAUQe6FvqQHahARIAMoAlAhFyADKAJUIRggAygCWCEZIAMoAlwhBCADIA42AmwgAyANNgJoIAMgDDYCZCADIAg2AmAgAyAENgJ8IAMgGTYCeCADIBg2AnQgAyAXNgJwIAkgCiALIBBB+PvjmQdrIBJB7I/e2QdrEBEgAygCUCEFIAMoAlQhBiADKAJYIQcgAygCXCEIIAMgAjYCXCADIB02AlggAyAWNgJUIAMgFTYCUCADIBw2AmwgAyAbNgJoIAMgGjYCZCADIBE2AmAgAyAUNgJ8IAMgEzYCeCADIBI2AnQgAyAQNgJwIB4gCSAPIAogCxAQIAMoAkAhFSADKAJEIRYgAygCSCECIAMoAkwhDyADIAQ2AmwgAyAZNgJoIAMgGDYCZCADIBc2AmAgAyAINgJ8IAMgBzYCeCADIAY2AnQgAyAFNgJwIAkgCiALIAJBlaa+3QVrIA9BhoCE+gZrEBEgAygCUCECIAMoAlQhDyADKAJYIREgAygCXCEQIAMgCDYCbCADIAc2AmggAyAGNgJkIAMgBTYCYCADIBA2AnwgAyARNgJ4IAMgDzYCdCADIAI2AnAgCSAKIAsgFUGOjrrMA2sgFkGJuJmIBGsQESAQICZqISYgESAlaiElIA8gJGohJCACICNqISMgAygCXCAiaiEiIAMoAlggIWohISADKAJUICBqISAgAygCUCAfaiEfIAFBQGsiASAnRw0ACyAAICY2AhwgACAlNgIYIAAgIjYCFCAAICE2AhAgACAkNgIMIAAgIzYCCCAAICA2AgQgACAfNgIAIANBgAFqJAALvx8CCH8BfgJAAkACQAJAAkAgAEH1AU8EQCAAQc3/e08NBSAAQQtqIgBBeHEhBEHMicAAKAIAIghFDQRBACAEayEBAn9BACAEQYACSQ0AGkEfIARB////B0sNABogBEEGIABBCHZnIgBrdkEBcSAAQQF0a0E+agsiB0ECdEGwhsAAaigCACICRQRAQQAhAAwCBQtBACEAIARBGSAHQQF2a0EfcUEAIAdBH0cbdCEGA0ACQCACKAIEQXhxIgUgBEkNACAFIARrIgUgAU8NACACIQMgBSIBDQBBACEBIAIhAAwECyACQRRqKAIAIgUgACAFIAIgBkEddkEEcWpBEGooAgAiAkcbIAAgBRshACAGQQF0IQYgAg0ACwwBBQtByInAACgCACIBQRAgAEELakF4cSAAQQtJGyIEQQN2IgJ2IgBBA3EEQAJAIABBf3NBAXEgAmoiAEEDdCIEQciHwABqKAIAIgJBCGoiBSgCACIDIARBwIfAAGoiBEcEQCADIAQ2AgwgBCADNgIIDAEFC0HIicAAIAFBfiAAd3E2AgALIAIgAEEDdCIAQQNyNgIEIAAgAmoiACAAKAIEQQFyNgIEIAUPBQsgBEHQicAAKAIATQ0DAkACQAJAAkACQAJAIABFBEBBzInAACgCACIARQ0KIABoQQJ0QbCGwABqKAIAIgYoAgRBeHEgBGshAgJAIAYoAhAiAEUEQCAGQRRqKAIAIgBFDQEFCwNAIAAoAgRBeHEgBGsiBSACSSEDIAUgAiADGyECIAAgBiADGyEGIAAoAhAiAQR/IAEFIABBFGooAgALIgANAAsLIAYQDiACQRBJDQIgBiAEQQNyNgIEIAQgBmoiBCACQQFyNgIEIAIgBGogAjYCAEHQicAAKAIAIgMNAQwFBQsCQEECIAJBH3EiAnQiA0EAIANrciAAIAJ0cWgiAkEDdCIFQciHwABqKAIAIgBBCGoiBigCACIDIAVBwIfAAGoiBUcEQCADIAU2AgwgBSADNgIIDAEFC0HIicAAIAFBfiACd3E2AgALIAAgBEEDcjYCBCAAIARqIgUgAkEDdCIBIARrIgJBAXI2AgQgACABaiACNgIAQdCJwAAoAgAiAw0CDAMLIANBeHFBwIfAAGohAEHYicAAKAIAIQECf0HIicAAKAIAIgVBASADQQN2dCIDcUUEQEHIicAAIAMgBXI2AgAgAAwBBQsgACgCCAshAyAAIAE2AgggAyABNgIMIAEgADYCDCABIAM2AggMAwsgBiACIARqIgBBA3I2AgQgACAGaiIAIAAoAgRBAXI2AgQMAwsgA0F4cUHAh8AAaiEAQdiJwAAoAgAhAQJ/QciJwAAoAgAiBEEBIANBA3Z0IgNxRQRAQciJwAAgAyAEcjYCACAADAEFCyAAKAIICyEEIAAgATYCCCAEIAE2AgwgASAANgIMIAEgBDYCCAtB2InAACAFNgIAQdCJwAAgAjYCACAGDwtB2InAACAENgIAQdCJwAAgAjYCAAsgBkEIag8LIAAgA3JFBEBBACEDIAhBAiAHdCIAQQAgAGtycSIARQ0DIABoQQJ0QbCGwABqKAIAIQAFCyAARQ0BCwNAIAAgAyAAKAIEQXhxIgUgBGsiBiABSSIHGyEIIAAoAhAiAkUEQCAAQRRqKAIAIQIFCyADIAggBCAFSyIAGyEDIAEgBiABIAcbIAAbIQEgAiIADQALCyADRQ0AIARB0InAACgCACIATSABIAAgBGtPcQ0AIAMQDgJAIAFBEE8EQCADIARBA3I2AgQgAyAEaiICIAFBAXI2AgQgASACaiABNgIAIAFBgAJPBEAgAiABEA0MAgULIAFBeHFBwIfAAGohAAJ/QciJwAAoAgAiBEEBIAFBA3Z0IgFxRQRAQciJwAAgASAEcjYCACAADAEFCyAAKAIICyEBIAAgAjYCCCABIAI2AgwgAiAANgIMIAIgATYCCAwBBQsgAyABIARqIgBBA3I2AgQgACADaiIAIAAoAgRBAXI2AgQLIANBCGoPCwJAAkACQAJAAkACQAJAIARB0InAACgCACIBSwRAIARB1InAACgCACIATwRAQQAhASAEQa+ABGoiAEEQdkAAIgJBf0YiBQ0JIAJBEHQiA0UNCUHgicAAQQAgAEGAgHxxIAUbIgZB4InAACgCAGoiADYCAEHkicAAQeSJwAAoAgAiASAAIAAgAUkbNgIAAkACQEHcicAAKAIAIgUEQEGwh8AAIQADQCAAKAIAIgEgACgCBCICaiADRg0CIAAoAggiAA0ACwwCBQtB7InAACgCACIAQQAgACADTRtFBEBB7InAACADNgIABQtB8InAAEH/HzYCAEG0h8AAIAY2AgBBsIfAACADNgIAQcyHwABBwIfAADYCAEHUh8AAQciHwAA2AgBByIfAAEHAh8AANgIAQdyHwABB0IfAADYCAEHQh8AAQciHwAA2AgBB5IfAAEHYh8AANgIAQdiHwABB0IfAADYCAEHsh8AAQeCHwAA2AgBB4IfAAEHYh8AANgIAQfSHwABB6IfAADYCAEHoh8AAQeCHwAA2AgBB/IfAAEHwh8AANgIAQfCHwABB6IfAADYCAEGEiMAAQfiHwAA2AgBB+IfAAEHwh8AANgIAQbyHwABBADYCAEGMiMAAQYCIwAA2AgBBgIjAAEH4h8AANgIAQYiIwABBgIjAADYCAEGUiMAAQYiIwAA2AgBBkIjAAEGIiMAANgIAQZyIwABBkIjAADYCAEGYiMAAQZCIwAA2AgBBpIjAAEGYiMAANgIAQaCIwABBmIjAADYCAEGsiMAAQaCIwAA2AgBBqIjAAEGgiMAANgIAQbSIwABBqIjAADYCAEGwiMAAQaiIwAA2AgBBvIjAAEGwiMAANgIAQbiIwABBsIjAADYCAEHEiMAAQbiIwAA2AgBBwIjAAEG4iMAANgIAQcyIwABBwIjAADYCAEHUiMAAQciIwAA2AgBByIjAAEHAiMAANgIAQdyIwABB0IjAADYCAEHQiMAAQciIwAA2AgBB5IjAAEHYiMAANgIAQdiIwABB0IjAADYCAEHsiMAAQeCIwAA2AgBB4IjAAEHYiMAANgIAQfSIwABB6IjAADYCAEHoiMAAQeCIwAA2AgBB/IjAAEHwiMAANgIAQfCIwABB6IjAADYCAEGEicAAQfiIwAA2AgBB+IjAAEHwiMAANgIAQYyJwABBgInAADYCAEGAicAAQfiIwAA2AgBBlInAAEGIicAANgIAQYiJwABBgInAADYCAEGcicAAQZCJwAA2AgBBkInAAEGIicAANgIAQaSJwABBmInAADYCAEGYicAAQZCJwAA2AgBBrInAAEGgicAANgIAQaCJwABBmInAADYCAEG0icAAQaiJwAA2AgBBqInAAEGgicAANgIAQbyJwABBsInAADYCAEGwicAAQaiJwAA2AgBBxInAAEG4icAANgIAQbiJwABBsInAADYCAEHcicAAIAM2AgBBwInAAEG4icAANgIAQdSJwAAgBkEoayIANgIAIAMgAEEBcjYCBCAAIANqQSg2AgRB6InAAEGAgIABNgIADAoLIAAoAgwgASAFS3INACADIAVLDQMLQeyJwABB7InAACgCACIAIAMgACADSRs2AgAgAyAGaiECQbCHwAAhAAJAAkADQCACIAAoAgBHBEAgACgCCCIADQEMAgULCyAAKAIMRQ0BC0Gwh8AAIQADQAJAIAUgACgCACIBTwRAIAEgACgCBGoiAiAFSw0BBQsgACgCCCEADAELC0HcicAAIAM2AgBB1InAACAGQShrIgA2AgAgAyAAQQFyNgIEIAAgA2pBKDYCBEHoicAAQYCAgAE2AgAgBSACQSBrQXhxQQhrIgAgACAFQRBqSRsiAUEbNgIEQbCHwAApAgAhCSABQRBqQbiHwAApAgA3AgAgASAJNwIIQbSHwAAgBjYCAEGwh8AAIAM2AgBBuIfAACABQQhqNgIAQbyHwABBADYCACABQRxqIQADQCAAQQc2AgAgAEEEaiIAIAJJDQALIAEgBUYNCSABIAEoAgRBfnE2AgQgBSABIAVrIgBBAXI2AgQgASAANgIAIABBgAJPBEAgBSAAEA0MCgULIABBeHFBwIfAAGohAQJ/QciJwAAoAgAiAkEBIABBA3Z0IgBxRQRAQciJwAAgACACcjYCACABDAEFCyABKAIICyEAIAEgBTYCCCAAIAU2AgwgBSABNgIMIAUgADYCCAwJCyAAIAM2AgAgACAAKAIEIAZqNgIEIAMgBEEDcjYCBCACIAMgBGoiBWshASACQdyJwAAoAgBGDQMgAkHYicAAKAIARg0EIAIoAgQiBEEDcUEBRgRAAkAgBEF4cSIAQYACTwRAIAIQDgwBBQsgAkEMaigCACIGIAJBCGooAgAiB0cEQCAHIAY2AgwgBiAHNgIIDAEFC0HIicAAQciJwAAoAgBBfiAEQQN2d3E2AgALIAAgAmoiAigCBCEEIAAgAWohAQULIAIgBEF+cTYCBCAFIAFBAXI2AgQgASAFaiABNgIAIAFBgAJPBEAgBSABEA0MCAULIAFBeHFBwIfAAGohAAJ/QciJwAAoAgAiAkEBIAFBA3Z0IgFxRQRAQciJwAAgASACcjYCACAADAEFCyAAKAIICyEBIAAgBTYCCCABIAU2AgwgBSAANgIMIAUgATYCCAwHBQtB1InAACAAIARrIgE2AgBB3InAAEHcicAAKAIAIgAgBGoiAjYCACACIAFBAXI2AgQgACAEQQNyNgIEIABBCGohAQwIBQtB2InAACgCACEAIAEgBGsiAkEQSQ0DQdCJwAAgAjYCAEHYicAAIAAgBGoiAzYCACADIAJBAXI2AgQgACABaiACNgIAIAAgBEEDcjYCBAwECyAAIAIgBmo2AgRB3InAAEHcicAAKAIAIgBBD2pBeHEiAUEIayICNgIAQdSJwABB1InAACgCACAGaiIDIAAgAWtqQQhqIgE2AgAgAiABQQFyNgIEIAAgA2pBKDYCBEHoicAAQYCAgAE2AgAMBQtB3InAACAFNgIAQdSJwABB1InAACgCACABaiIANgIAIAUgAEEBcjYCBAwDC0HYicAAIAU2AgBB0InAAEHQicAAKAIAIAFqIgA2AgAgBSAAQQFyNgIEIAAgBWogADYCAAwCC0HYicAAQQA2AgBB0InAAEEANgIAIAAgAUEDcjYCBCAAIAFqIgEgASgCBEEBcjYCBAsgAEEIag8LIANBCGoPC0EAIQFB1InAACgCACIAIARNDQBB1InAACAAIARrIgE2AgBB3InAAEHcicAAKAIAIgAgBGoiAjYCACACIAFBAXI2AgQgACAEQQNyNgIEIABBCGoPCyABC/oLAQt/IAAoAgQhByAAKAIAIQUCQAJAAkAgASgCACIKIAEoAggiAHIEQAJAIABFDQAgBSAHaiEJIAFBDGooAgBBAWohBiAFIQIDQAJAIAIhACAGQQFrIgZFDQAgACAJRg0CAn8gACwAACIEQQBOBEAgBEH/AXEhBCAAQQFqDAEFCyAALQABQT9xIQggBEEfcSECIARBX00EQCACQQZ0IAhyIQQgAEECagwBBQsgAC0AAkE/cSAIQQZ0ciEIIARBcEkEQCAIIAJBDHRyIQQgAEEDagwBBQsgAkESdEGAgPAAcSAALQADQT9xIAhBBnRyciIEQYCAxABGDQMgAEEEagsiAiADIABraiEDIARBgIDEAEcNAQwCCwsgACAJRg0AIAAsAAAiAkEATiACQWBJciACQXBJckUEQCACQf8BcUESdEGAgPAAcSAALQADQT9xIAAtAAJBP3FBBnQgAC0AAUE/cUEMdHJyckGAgMQARg0BBQsCQAJAIANFDQAgAyAHTwRAQQAhACADIAdGDQEMAgULQQAhACADIAVqLAAAQUBIDQELIAUhAAsgAyAHIAAbIQcgACAFIAAbIQULIApFDQMgASgCBCELIAdBEE8EQCAHIAUgBUEDakF8cSIEayIGaiIKQQNxIQhBACEJQQAhACAEIAVHBEAgBCAFQX9zakEDTwRAQQAhAwNAIAAgAyAFaiICLAAAQb9/SmogAkEBaiwAAEG/f0pqIAJBAmosAABBv39KaiACQQNqLAAAQb9/SmohACADQQRqIgMNAAsFCyAFIQIDQCAAIAIsAABBv39KaiEAIAJBAWohAiAGQQFqIgYNAAsFCwJAIAhFDQAgBCAKQXxxaiICLAAAQb9/SiEJIAhBAUYNACAJIAIsAAFBv39KaiEJIAhBAkYNACAJIAIsAAJBv39KaiEJCyAKQQJ2IQggACAJaiEDA0AgBCEGIAhFDQRBwAEgCCAIQcABTxsiCUEDcSEKIAlBAnQhBEEAIQIgCUEETwRAIAYgBEHwB3FqIQwgBiEAA0AgAiAAKAIAIgJBf3NBB3YgAkEGdnJBgYKECHFqIABBBGooAgAiAkF/c0EHdiACQQZ2ckGBgoQIcWogAEEIaigCACICQX9zQQd2IAJBBnZyQYGChAhxaiAAQQxqKAIAIgJBf3NBB3YgAkEGdnJBgYKECHFqIQIgAEEQaiIAIAxHDQALBQsgCCAJayEIIAQgBmohBCACQQh2Qf+B/AdxIAJB/4H8B3FqQYGABGxBEHYgA2ohAyAKRQ0ACyAGIAlB/AFxQQJ0aiICKAIAIgBBf3NBB3YgAEEGdnJBgYKECHEhACAKQQFGDQIgACACKAIEIgBBf3NBB3YgAEEGdnJBgYKECHFqIQAgCkECRg0CIAAgAigCCCIAQX9zQQd2IABBBnZyQYGChAhxaiEADAIFCyAHRQRAQQAhAwwDBQsgB0EDcSECAkAgB0EESQRAQQAhA0EAIQYMAQULQQAhAyAFIQAgB0F8cSIGIQQDQCADIAAsAABBv39KaiAAQQFqLAAAQb9/SmogAEECaiwAAEG/f0pqIABBA2osAABBv39KaiEDIABBBGohACAEQQRrIgQNAAsLIAJFDQIgBSAGaiEAA0AgAyAALAAAQb9/SmohAyAAQQFqIQAgAkEBayICDQALDAIFCwwCCyAAQQh2Qf+BHHEgAEH/gfwHcWpBgYAEbEEQdiADaiEDCwJAIAMgC0kEQCALIANrIQNBACEAAkACQAJAIAEtACBBAWsOAgABAgsgAyEAQQAhAwwBCyADQQF2IQAgA0EBakEBdiEDCyAAQQFqIQAgAUEYaigCACECIAEoAhAhBiABKAIUIQEDQCAAQQFrIgBFDQIgASAGIAIoAhARBABFDQALQQEPBQsMAQtBASEAIAEgBSAHIAIoAgwRBgAEfyAABUEAIQACfwNAIAMgACADRg0BGiAAQQFqIQAgASAGIAIoAhARBABFDQALIABBAWsLIANJCw8LIAEoAhQgBSAHIAFBGGooAgAoAgwRBgAL3AoCBn8DfiMAQcADayIJJAAgCSACNgLYASAJIAI2AtQBIAkgATYC0AEgCUEgaiAJQdABaiICEBYgCSgCJCEBIAkoAiAhCyAJIAQ2AtgBIAkgBDYC1AEgCSADNgLQASAJQRhqIAIQFiAJKAIcIQwgCSgCGCENIAkgBjYC2AEgCSAGNgLUASAJIAU2AtABIAlBEGogAhAWIAkoAhQhBSAJKAIQIQYgCSAINgLYASAJIAg2AtQBIAkgBzYC0AEgCUEIaiACEBYgCSgCDCEHIAkoAgghCAJAAkACQAJAIAFFBEBBASECDAEFCyABQQBIDQFBlIrAAC0AABogARABIgJFDQILIAIgCyABEAwhAiAJIAE2AjwgCSABNgI4IAkgAjYCNCAJQTRqIgIgDSAMEAsgAiAGIAUQCyACIAggBxALIAJBqIXAAEEgEAsgCUHoAGpBwQAQFCEEIAlB2ABqQaCFwAApAwA3AwAgCUHQAGpBmIXAACkDADcDACAJQcgAakGQhcAAKQMANwMAIAlCADcDYCAJQYiFwAApAwA3A0AgCSgCNCEDAkAgCSgCPCICQT9NBEAgBCADIAIQDBoMAQULIAkgAkEGdiIKrTcDYCAJQUBrIAMgChAAIAQgAyACQUBxaiACQT9xIgIQDBoLIAkgAjoAqAEgCUHQAWogCUFAa0HwABAMGiAJQdgCakIANwMAIAlB0AJqQgA3AwAgCUHIAmpCADcDACAJQgA3A8ACIAlB+AJqQgA3AwAgCUHwAmpCADcDACAJQegCakIANwMAIAlB+AFqIgQgCUG4AmotAAAiAmoiCkGAAToAACAJQgA3A+ACIAkpA/ABIg9CAYZCgICA+A+DIA9CD4hCgID8B4OEIA9CH4hCgP4DgyAPQgmGIg9COIiEhCEQIAKtIhFCO4YgDyARQgOGhCIPQoD+A4NCKIaEIA9CgID8B4NCGIYgD0KAgID4D4NCCIaEhCACQT9zIg4EQCAKQQFqIA4QFBoFCyAQhCEPAkAgAkE4cUE4RwRAIAlBsAJqIA83AwAgCUHQAWogBEEBEAAMAQULIAlB0AFqIgIgBEEBEAAgCUGAA2oiBEE4EBQaIAkgDzcAuAMgAiAEQQEQAAtBACECIAlBADoAuAIDQCAJQeACaiACaiAJQdABaiACaigCACIEQRh0IARBgP4DcUEIdHIgBEEIdkGA/gNxIARBGHZycjYAACACQQRqIgJBIEcNAAsgCUGIA2ogCUHoAmopAwA3AwAgCUGQA2ogCUHwAmopAwA3AwAgCUGYA2ogCUH4AmopAwA3AwAgCSAJKQPgAjcDgAMgCUEFNgLMASAJQciFwAA2ArABIAlBATYCtAEgCUEANgLAASAJIAlBgANqNgLIASAJQbwBakEBNgIAIAkgCUHIAWo2ArgBIAlBADYC2AEgCUIBNwLQASAJQdABaiAJQbABahAHDQIgCUEwaiAJQdgBaigCADYCACAJIAkpAtABNwMoIAkoAjgEQCADEAQFCyAHBEAgCBAEBQsgBQRAIAYQBAULIAwEQCANEAQFCyABBEAgCxAEBQsgCUHYAWogCUEwaigCADYCACAJIAkpAyg3A9ABIAkgCUHQAWoQFiAAIAkpAwA3AwAgCUHAA2okAA8LEBkACwALIwBBQGoiACQAIABBMzYCDCAAQdCBwAA2AgggAEGEgsAANgIUIAAgCUHgAmo2AhAgAEEkakICNwIAIABBPGpBAzYCACAAQQI2AhwgAEHQgsAANgIYIABBBDYCNCAAIABBMGo2AiAgACAAQRBqNgI4IAAgAEEIajYCMCAAQRhqQayCwAAQEgALoAcBBX8gAEEIayIBIABBBGsoAgAiA0F4cSIAaiECAkACQAJAAkAgA0EBcQ0AIANBA3FFDQEgASgCACIDIABqIQAgASADayIBQdiJwAAoAgBGBEAgAigCBEEDcUEDRw0BQdCJwAAgADYCACACIAIoAgRBfnE2AgQgASAAQQFyNgIEIAIgADYCAA8FCyADQYACTwRAIAEQDgwBBQsgAUEMaigCACIEIAFBCGooAgAiBUcEQCAFIAQ2AgwgBCAFNgIIDAEFC0HIicAAQciJwAAoAgBBfiADQQN2d3E2AgALAkACQCACKAIEIgNBAnFFBEAgAkHcicAAKAIARg0CIAJB2InAACgCAEYNBSADQXhxIgQgAGohAAJAIARBgAJPBEAgAhAODAEFCyACQQxqKAIAIgQgAkEIaigCACICRwRAIAIgBDYCDCAEIAI2AggMAQULQciJwABByInAACgCAEF+IANBA3Z3cTYCAAsgASAAQQFyNgIEIAAgAWogADYCACABQdiJwAAoAgBHDQFB0InAACAANgIADwULIAIgA0F+cTYCBCABIABBAXI2AgQgACABaiAANgIACyAAQYACSQ0CIAEgABANQQAhAUHwicAAQfCJwAAoAgBBAWsiADYCACAADQFBuIfAACgCACIABEADQCABQQFqIQEgACgCCCIADQALBQtB8InAAEH/HyABIAFB/x9NGzYCAA8LQdyJwAAgATYCAEHUicAAQdSJwAAoAgAgAGoiADYCACABIABBAXI2AgRB2InAACgCACABRgRAQdCJwABBADYCAEHYicAAQQA2AgAFCyAAQeiJwAAoAgAiA00NAEHcicAAKAIAIgJFDQBBACEBAkBB1InAACgCACIEQSlJDQBBsIfAACEAA0AgAiAAKAIAIgVPBEAgBSAAKAIEaiACSw0CBQsgACgCCCIADQALC0G4h8AAKAIAIgAEQANAIAFBAWohASAAKAIIIgANAAsFC0HwicAAQf8fIAEgAUH/H00bNgIAIAMgBE8NAEHoicAAQX82AgALDwsgAEF4cUHAh8AAaiECAn9ByInAACgCACIDQQEgAEEDdnQiAHFFBEBByInAACAAIANyNgIAIAIMAQULIAIoAggLIQAgAiABNgIIIAAgATYCDCABIAI2AgwgASAANgIIDwtB2InAACABNgIAQdCJwABB0InAACgCACAAaiIANgIAIAEgAEEBcjYCBCAAIAFqIAA2AgALwwYCDH8CfiMAQTBrIgYkAEEnIQICQCAANQIAIg5CkM4AVARAIA4hDwwBBQsDQCAGQQlqIAJqIgBBBGsgDkKQzgCAIg9C8LEDfiAOfKciA0H//wNxQeQAbiIEQQF0QeCCwABqLwAAOwAAIABBAmsgBEGcf2wgA2pB//8DcUEBdEHggsAAai8AADsAACACQQRrIQIgDkL/wdcvViAPIQ4NAAsLIA+nIgBB4wBLBEAgAkECayICIAZBCWpqIA+nIgNB//8DcUHkAG4iAEGcf2wgA2pB//8DcUEBdEHggsAAai8AADsAAAULAkAgAEEKTwRAIAJBAmsiAiAGQQlqaiAAQQF0QeCCwABqLwAAOwAADAEFCyACQQFrIgIgBkEJamogAEEwajoAAAtBJyACayEEQQEhA0ErQYCAxAAgASgCHCIAQQFxIgUbIQggAEEddEEfdUGohsAAcSEJIAZBCWogAmohCgJAIAEoAgBFBEAgASgCFCIAIAEoAhgiASAIIAkQGg0BIAAgCiAEIAEoAgwRBgAhAwwBBQsgASgCBCIHIAQgBWoiA00EQEEBIQMgASgCFCIAIAEoAhgiASAIIAkQGg0BIAAgCiAEIAEoAgwRBgAhAwwBBQsgAEEIcQRAIAEoAhAhDCABQTA2AhAgAS0AICENQQEhAyABQQE6ACAgASgCFCIAIAEoAhgiCyAIIAkQGg0BIAIgB2ogBWtBJmshAgNAIAJBAWsiAgRAIABBMCALKAIQEQQARQ0BDAMFCwsgACAKIAQgCygCDBEGAA0BIAEgDToAICABIAw2AhBBACEDDAEFCyAHIANrIQACQAJAAkAgAS0AICICQQFrDgMAAQACCyAAIQJBACEADAELIABBAXYhAiAAQQFqQQF2IQALIAJBAWohAiABQRhqKAIAIQUgASgCECEHIAEoAhQhAQJAA0AgAkEBayICRQ0BIAEgByAFKAIQEQQARQ0AC0EBIQMMAQtBASEDIAEgBSAIIAkQGg0AIAEgCiAEIAUoAgwRBgANAEEAIQIDQCAAIAJGBEBBACEDDAIFCyACQQFqIQIgASAHIAUoAhARBABFDQALIAJBAWsgAEkhAwsgBkEwaiQAIAMLlAYBBn8CQAJAAkACQCACQQlPBEAgAiADEAoiAg0BQQAPBQtBACECIANBzP97Sw0BQRAgA0ELakF4cSADQQtJGyEBIABBBGsiBigCACIHQXhxIQQCQAJAAkACQAJAAkACQCAHQQNxBEAgAEEIayIIIARqIQUgASAETQ0BIAVB3InAACgCAEYNBiAFQdiJwAAoAgBGDQQgBSgCBCIHQQJxDQcgB0F4cSIJIARqIgQgAUkNByAEIAFrIQIgCUGAAkkNAiAFEA4MAwULIAFBgAJJIAQgAUEEcklyIAQgAWtBgYAIT3INBgwKCyAEIAFrIgJBEE8NAwwJCyAFQQxqKAIAIgMgBUEIaigCACIFRwRAIAUgAzYCDCADIAU2AggMAQULQciJwABByInAACgCAEF+IAdBA3Z3cTYCAAsgAkEQTwRAIAYgBigCAEEBcSABckECcjYCACABIAhqIgEgAkEDcjYCBCAEIAhqIgMgAygCBEEBcjYCBCABIAIQCAwIBQsgBiAGKAIAQQFxIARyQQJyNgIAIAQgCGoiASABKAIEQQFyNgIEDAcLQdCJwAAoAgAgBGoiBCABSQ0CAkAgBCABayIDQQ9NBEAgBiAHQQFxIARyQQJyNgIAIAQgCGoiASABKAIEQQFyNgIEQQAhAwwBBQsgBiAHQQFxIAFyQQJyNgIAIAEgCGoiAiADQQFyNgIEIAQgCGoiASADNgIAIAEgASgCBEF+cTYCBAtB2InAACACNgIAQdCJwAAgAzYCAAwGCyAGIAdBAXEgAXJBAnI2AgAgASAIaiIBIAJBA3I2AgQgBSAFKAIEQQFyNgIEIAEgAhAIDAULQdSJwAAoAgAgBGoiBCABSw0DCyADEAEiAUUNASABIABBfEF4IAYoAgAiAUEDcRsgAUF4cWoiASADIAEgA0kbEAwgABAEDwsgAiAAIAEgAyABIANJGxAMGiAAEAQLIAIPCyAGIAdBAXEgAXJBAnI2AgAgASAIaiICIAQgAWsiAUEBcjYCBEHUicAAIAE2AgBB3InAACACNgIAIAAPCyAAC4wFAQt/IwBBMGsiAiQAIAJBJGpB8IDAADYCACACQQM6ACwgAkEgNgIcIAJBADYCKCACIAA2AiAgAkEANgIUIAJBADYCDAJ/AkACQAJAIAEoAhAiCkUEQCABQQxqKAIAIgBFDQEgASgCCCEDIABBA3QhBSAAQQFrQf////8BcUEBaiEHIAEoAgAhAANAIABBBGooAgAiBARAIAIoAiAgACgCACAEIAIoAiQoAgwRBgANBAULIAMoAgAgAkEMaiADQQRqKAIAEQQADQMgA0EIaiEDIABBCGohACAFQQhrIgUNAAsMAQULIAFBFGooAgAiAEUNACAAQQV0IQsgAEEBa0H///8/cUEBaiEHIAEoAgghCCABKAIAIQADQCAAQQRqKAIAIgMEQCACKAIgIAAoAgAgAyACKAIkKAIMEQYADQMFCyACIAUgCmoiA0EQaigCADYCHCACIANBHGotAAA6ACwgAiADQRhqKAIANgIoIANBDGooAgAhBkEAIQlBACEEAkACQAJAIANBCGooAgBBAWsOAgACAQsgBkEDdCAIaiIMKAIEQQJHDQEgDCgCACgCACEGC0EBIQQLIAIgBjYCECACIAQ2AgwgA0EEaigCACEEAkACQAJAIAMoAgBBAWsOAgACAQsgBEEDdCAIaiIGKAIEQQJHDQEgBigCACgCACEEC0EBIQkLIAIgBDYCGCACIAk2AhQgCCADQRRqKAIAQQN0aiIDKAIAIAJBDGogAygCBBEEAA0CIABBCGohACALIAVBIGoiBUcNAAsLIAcgASgCBE8NASACKAIgIAEoAgAgB0EDdGoiACgCACAAKAIEIAIoAiQoAgwRBgBFDQELQQEMAQtBAAsgAkEwaiQAC5gFAQR/IAAgAWohAgJAAkACQCAAKAIEIgNBAXENACADQQNxRQ0BIAAoAgAiAyABaiEBIAAgA2siAEHYicAAKAIARgRAIAIoAgRBA3FBA0cNAUHQicAAIAE2AgAgAiACKAIEQX5xNgIEIAAgAUEBcjYCBCACIAE2AgAPBQsgA0GAAk8EQCAAEA4MAQULIABBDGooAgAiBCAAQQhqKAIAIgVHBEAgBSAENgIMIAQgBTYCCAwBBQtByInAAEHIicAAKAIAQX4gA0EDdndxNgIACwJAAkAgAigCBCIDQQJxRQRAIAJB3InAACgCAEYNAiACQdiJwAAoAgBGDQQgA0F4cSIEIAFqIQECQCAEQYACTwRAIAIQDgwBBQsgAkEMaigCACIEIAJBCGooAgAiAkcEQCACIAQ2AgwgBCACNgIIDAEFC0HIicAAQciJwAAoAgBBfiADQQN2d3E2AgALIAAgAUEBcjYCBCAAIAFqIAE2AgAgAEHYicAAKAIARw0BQdCJwAAgATYCAA8FCyACIANBfnE2AgQgACABQQFyNgIEIAAgAWogATYCAAsgAUGAAk8EQCAAIAEQDQ8FCyABQXhxQcCHwABqIQICf0HIicAAKAIAIgNBASABQQN2dCIBcUUEQEHIicAAIAEgA3I2AgAgAgwBBQsgAigCCAshASACIAA2AgggASAANgIMIAAgAjYCDCAAIAE2AggPC0HcicAAIAA2AgBB1InAAEHUicAAKAIAIAFqIgE2AgAgACABQQFyNgIEIABB2InAACgCAEcNAEHQicAAQQA2AgBB2InAAEEANgIACw8LQdiJwAAgADYCAEHQicAAQdCJwAAoAgAgAWoiATYCACAAIAFBAXI2AgQgACABaiABNgIAC4EEAQV/IwBBEGsiAyQAAkACfwJAIAFBgAFPBEAgA0EANgIMIAFBgBBJDQEgAUGAgARJBEAgAyABQT9xQYABcjoADiADIAFBDHZB4AFyOgAMIAMgAUEGdkE/cUGAAXI6AA1BAwwDBQsgAyABQT9xQYABcjoADyADIAFBBnZBP3FBgAFyOgAOIAMgAUEMdkE/cUGAAXI6AA0gAyABQRJ2QQdxQfABcjoADEEEDAIFCyAAKAIIIgIgACgCBEYEQCMAQSBrIgQkAAJAAkAgAkEBaiICRQ0AQQggACgCBCIGQQF0IgUgAiACIAVJGyICIAJBCE0bIgVBf3NBH3YhAgJAIAZFBEAgBEEANgIYDAEFCyAEIAY2AhwgBEEBNgIYIAQgACgCADYCFAsgBEEIaiACIAUgBEEUahAVIAQoAgwhAiAEKAIIRQRAIAAgBTYCBCAAIAI2AgAMAgULIAJBgYCAgHhGDQEgAkUNAAALEBkACyAEQSBqJAAgACgCCCECBQsgACACQQFqNgIIIAAoAgAgAmogAToAAAwCCyADIAFBP3FBgAFyOgANIAMgAUEGdkHAAXI6AAxBAgshASABIAAoAgQgACgCCCICa0sEQCAAIAIgARATIAAoAgghAgULIAAoAgAgAmogA0EMaiABEAwaIAAgASACajYCCAsgA0EQaiQAQQAL6QIBBX8CQEHN/3tBECAAIABBEE0bIgBrIAFNDQAgAEEQIAFBC2pBeHEgAUELSRsiBGpBDGoQASICRQ0AIAJBCGshAQJAIABBAWsiAyACcUUEQCABIQAMAQULIAJBBGsiBSgCACIGQXhxIAIgA2pBACAAa3FBCGsiAiAAQQAgAiABa0EQTRtqIgAgAWsiAmshAyAGQQNxBEAgACAAKAIEQQFxIANyQQJyNgIEIAAgA2oiAyADKAIEQQFyNgIEIAUgBSgCAEEBcSACckECcjYCACABIAJqIgMgAygCBEEBcjYCBCABIAIQCAwBBQsgASgCACEBIAAgAzYCBCAAIAEgAmo2AgALAkAgACgCBCIBQQNxRQ0AIAFBeHEiAiAEQRBqTQ0AIAAgAUEBcSAEckECcjYCBCAAIARqIgEgAiAEayIEQQNyNgIEIAAgAmoiAiACKAIEQQFyNgIEIAEgBBAICyAAQQhqIQMLIAMLmwMBBn8gAiAAKAIEIAAoAggiA2tLBEAjAEEgayIFJAACQAJAIAMgAiADaiIESw0AQQggACgCBCIGQQF0IgMgBCADIARLGyIDIANBCE0bIgNBf3NBH3YhBwJAIAZFBEAgBUEANgIYDAEFCyAFIAY2AhwgBUEBNgIYIAUgACgCADYCFAsgBUEUaiEGIAVBCGoiBAJ/AkACfwJAAkAgBwRAIANBAEgNASAGKAIEBEACQCAGQQhqKAIAIghFBEAMAQULIAYoAgAgCCAHIAMQBgwFCwULIANFDQJBlIrAAC0AABogAxABDAMFCyAEQQA2AgQgBEEIaiADNgIADAMLIARBADYCBAwCCyAHCyIGBEAgBCAGNgIEIARBCGogAzYCAEEADAIFCyAEIAc2AgQgBEEIaiADNgIAC0EBCzYCACAFKAIMIQQgBSgCCEUEQCAAIAM2AgQgACAENgIADAIFCyAEQYGAgIB4Rg0BIARFDQAACxAZAAsgBUEgaiQAIAAoAgghAwULIAAoAgAgA2ogASACEAwaIAAgAiADajYCCAu8AgEHfwJAIAIiBEEQSQRAIAAhAgwBBQsgAEEAIABrQQNxIgNqIQUgAwRAIAAhAiABIQYDQCACIAYtAAA6AAAgBkEBaiEGIAJBAWoiAiAFSQ0ACwULIAUgBCADayIIQXxxIgdqIQICQCABIANqIgNBA3EEQCAHQQBMDQEgA0EDdCIEQRhxIQkgA0F8cSIGQQRqIQFBACAEa0EYcSEEIAYoAgAhBgNAIAUgBiAJdiABKAIAIgYgBHRyNgIAIAFBBGohASAFQQRqIgUgAkkNAAsMAQULIAdBAEwNACADIQEDQCAFIAEoAgA2AgAgAUEEaiEBIAVBBGoiBSACSQ0ACwsgCEEDcSEEIAMgB2ohAQsgBARAIAIgBGohAwNAIAIgAS0AADoAACABQQFqIQEgAkEBaiICIANJDQALBQsgAAuyAgEEf0EfIQIgAEIANwIQIAFB////B00EQCABQQYgAUEIdmciA2t2QQFxIANBAXRrQT5qIQIFCyAAIAI2AhwgAkECdEGwhsAAaiEEAkBBzInAACgCACIFQQEgAnQiA3FFBEBBzInAACADIAVyNgIAIAQgADYCACAAIAQ2AhgMAQULAkACQCABIAQoAgAiAygCBEF4cUYEQCADIQIMAQULIAFBGSACQQF2a0EfcUEAIAJBH0cbdCEEA0AgAyAEQR12QQRxakEQaiIFKAIAIgJFDQIgBEEBdCEEIAIhAyACKAIEQXhxIAFHDQALCyACKAIIIgEgADYCDCACIAA2AgggAEEANgIYIAAgAjYCDCAAIAE2AggPCyAFIAA2AgAgACADNgIYCyAAIAA2AgwgACAANgIIC7sCAQV/IAAoAhghAwJAAkAgACAAKAIMIgFGBEAgAEEUQRAgAEEUaiIBKAIAIgQbaigCACICDQFBACEBDAIFCyAAKAIIIgIgATYCDCABIAI2AggMAQsgASAAQRBqIAQbIQQDQCAEIQUgAiIBQRRqIgIgAUEQaiACKAIAIgIbIQQgAUEUQRAgAhtqKAIAIgINAAsgBUEANgIACwJAIANFDQACQCAAIAAoAhxBAnRBsIbAAGoiAigCAEcEQCADQRBBFCADKAIQIABGG2ogATYCACABDQEMAgULIAIgATYCACABDQBBzInAAEHMicAAKAIAQX4gACgCHHdxNgIADwsgASADNgIYIAAoAhAiAgRAIAEgAjYCECACIAE2AhgFCyAAQRRqKAIAIgBFDQAgAUEUaiAANgIAIAAgATYCGAsLqgIBBX8jAEFAaiICJAAgAUEMaigCACEDIAEoAgghBCACQcAAEBQhBUEgIANBwAAgBBsiA0EBdiADQQFxaiICIAJBIE8bIgQEQCAFIQIDQCACQQFqIAAtAAAiBkEPcUHxhMAAai0AADoAACACIAZBBHZB8YTAAGotAAA6AAAgAEEBaiEAIAJBAmohAiAEQQFrIgQNAAsFCyADQcEATwRAIwBBMGsiACQAIAAgAzYCACAAQcAANgIEIABBFGpCAjcCACAAQSxqQQE2AgAgAEECNgIMIABB3ITAADYCCCAAQQE2AiQgACAAQSBqNgIQIAAgAEEEajYCKCAAIAA2AiAgAEEIakHggMAAEBIABQsgASgCFCAFIAMgAUEYaigCACgCDBEGACAFQUBrJAAL6AEBA38gACADKAIIIAEoAgwgASgCCCIFQQ53IAVBGXdzIAVBA3ZzamogBCgCBCIGQQ93IAZBDXdzIAZBCnZzaiIGNgIMIAAgAygCBCAFIAEoAgQiB0EOdyAHQRl3cyAHQQN2c2pqIAQoAgAiBUEPdyAFQQ13cyAFQQp2c2oiBTYCCCAAIAMoAgAgByABKAIAIgFBDncgAUEZd3MgAUEDdnNqaiAGQQ93IAZBDXdzIAZBCnZzajYCBCAAIAQoAgwgASACQQ53IAJBGXdzIAJBA3ZzamogBUEPdyAFQQ13cyAFQQp2c2o2AgAL1gEBBX8gACABKAIMIAIoAggiBUEadyAFQRV3cyAFQQd3cyAEamogASgCCCIHIAIoAgwiCHMgBXEgB3NqIgQgASgCBGoiBjYCDCAAIAQgAigCACIEIAEoAgAiCSACKAIEIgJzcSACIAlxcyAEQR53IARBE3dzIARBCndzamoiATYCBCAAIAkgAyAHaiAIIAYgBSAIc3FzaiAGQRp3IAZBFXdzIAZBB3dzaiIDajYCCCAAIAFBHncgAUETd3MgAUEKd3MgASACIARzcSACIARxc2ogA2o2AgALogIBAX8jAEEgayICJAAgAkEBOwEcIAIgATYCGCACIAA2AhQgAkG8gsAANgIQIAJBqIbAADYCDCACQQxqIgAoAggiAUUEQCMAQSBrIgAkACAAQQxqQgA3AgAgAEEBNgIEIABBqIbAADYCCCAAQSs2AhwgAEHQhcAANgIYIAAgAEEYajYCACAAQZiGwAAQEgAFCyABQQxqKAIAIQICQAJAIAEoAgQOAgAAAQsgAg0ACyAALQAQIQEgAC0AERpBrIbAAEGshsAAKAIAIgBBAWo2AgACQCAAQQBIDQBB+InAAC0AAEEBcQ0AQfiJwABBAToAAEH0icAAQfSJwAAoAgBBAWo2AgBBqIbAACgCAEEASA0AQfiJwABBADoAACABRQ0AAAsAC74BAQJ/IwBBIGsiAyQAAkACQCABIAEgAmoiAUsNAEEIIAAoAgQiAkEBdCIEIAEgASAESRsiASABQQhNGyIEQX9zQR92IQECQCACRQRAIANBADYCGAwBBQsgAyACNgIcIANBATYCGCADIAAoAgA2AhQLIANBCGogASAEIANBFGoQFSADKAIMIQEgAygCCEUEQCAAIAQ2AgQgACABNgIADAIFCyABQYGAgIB4Rg0BIAFFDQAACxAZAAsgA0EgaiQAC6MBAQN/AkAgASICQRBJBEAgACEBDAEFCyAAQQAgAGtBA3EiBGohAyAEBEAgACEBA0AgAUEAOgAAIAFBAWoiASADSQ0ACwULIAMgAiAEayICQXxxIgRqIQEgBEEASgRAA0AgA0EANgIAIANBBGoiAyABSQ0ACwULIAJBA3EhAgsgAgRAIAEgAmohAgNAIAFBADoAACABQQFqIgEgAkkNAAsFCyAAC6IBAAJAAkAgAQRAIAJBAEgNAQJ/IAMoAgQEQAJAIANBCGooAgAiAUUEQAwBBQsgAygCACABQQEgAhAGDAILBQtBlIrAAC0AABogAhABCyIBBEAgACABNgIEIABBCGogAjYCACAAQQA2AgAPBQsgAEEBNgIEDAIFCyAAQQA2AgQMAQsgAEEANgIEIABBATYCAA8LIABBCGogAjYCACAAQQE2AgALaQEEfwJAIAEoAgQiAiABKAIIIgNLBEAgASgCACEEAkAgA0UEQCAEEARBASECDAEFCyADIQUgBCACQQEgAxAGIgJFDQILIAEgBTYCBCABIAI2AgAFCyAAIAM2AgQgACABKAIANgIADwsAC0oAAkAgAWlBAUdBgICAgHggAWsgAElyDQAgAARAQZSKwAAtAAAaAn8gAUEJTwRAIAEgABAKDAEFCyAAEAELIgFFDQEFCyABDwsAC0IBAX8gAiAAKAIEIAAoAggiA2tLBEAgACADIAIQEyAAKAIIIQMFCyAAKAIAIANqIAEgAhAMGiAAIAIgA2o2AghBAAs/AQF/IwBBIGsiACQAIABBFGpCADcCACAAQQE2AgwgAEG4gcAANgIIIABBqIbAADYCECAAQQhqQcCBwAAQEgALOgACQAJ/IAJBgIDEAEcEQEEBIAAgAiABKAIQEQQADQEaBQsgAw0BQQALDwsgACADQQAgASgCDBEGAAsuAAJAIANpQQFHQYCAgIB4IANrIAFJckUEQCAAIAEgAyACEAYiAA0BBQsACyAACxwAIAEoAhRB7ITAAEEFIAFBGGooAgAoAgwRBgALFAAgACgCACABIAAoAgQoAgwRBAALEgAgACgCBARAIAAoAgAQBAULCyEAIABCkL28l+OV96AyNwMIIABCg+W4qNm60bGrfzcDAAsOACAAKAIAGgNADAALAAsLACAAIwBqJAAjAAsMACABBEAgABAEBQsLCAAgACABEAcLAgALC68GAQBBgIDAAAulBi9Vc2Vycy95cy8uY2FyZ28vcmVnaXN0cnkvc3JjL2luZGV4LmNyYXRlcy5pby02ZjE3ZDIyYmJhMTUwMDFmL2dlbmVyaWMtYXJyYXktMC4xNC43L3NyYy9oZXgucnMAAAAAEABeAAAALgAAAD8AAAAGAAAADAAAAAQAAAAHAAAACAAAAAkAAABsaWJyYXJ5L2FsbG9jL3NyYy9yYXdfdmVjLnJzY2FwYWNpdHkgb3ZlcmZsb3cAAACkABAAEQAAAIgAEAAcAAAAFgIAAAUAAABhIGZvcm1hdHRpbmcgdHJhaXQgaW1wbGVtZW50YXRpb24gcmV0dXJuZWQgYW4gZXJyb3IACgAAAAAAAAABAAAACwAAAGxpYnJhcnkvYWxsb2Mvc3JjL2ZtdC5ycxQBEAAYAAAAYgIAACAAAAAKAAAAAAAAAAEAAAAMAAAAOiAAACgDEAAAAAAATAEQAAIAAAAwMDAxMDIwMzA0MDUwNjA3MDgwOTEwMTExMjEzMTQxNTE2MTcxODE5MjAyMTIyMjMyNDI1MjYyNzI4MjkzMDMxMzIzMzM0MzUzNjM3MzgzOTQwNDE0MjQzNDQ0NTQ2NDc0ODQ5NTA1MTUyNTM1NDU1NTY1NzU4NTk2MDYxNjI2MzY0NjU2NjY3Njg2OTcwNzE3MjczNzQ3NTc2Nzc3ODc5ODA4MTgyODM4NDg1ODY4Nzg4ODk5MDkxOTI5Mzk0OTU5Njk3OTg5OSBvdXQgb2YgcmFuZ2UgZm9yIHNsaWNlIG9mIGxlbmd0aCByYW5nZSBlbmQgaW5kZXggAABKAhAAEAAAACgCEAAiAAAARXJyb3IwMTIzNDU2Nzg5YWJjZGVmAAAAAAAAAGfmCWqFrme7cvNuPDr1T6V/Ug5RjGgFm6vZgx8ZzeBbYTNjYTQyZmNhODFlM2Y4OTVjOTljODcxOTRkODc0NTIoAxAAAAAAAGNhbGxlZCBgT3B0aW9uOjp1bndyYXAoKWAgb24gYSBgTm9uZWAgdmFsdWVsaWJyYXJ5L3N0ZC9zcmMvcGFuaWNraW5nLnJzAPsCEAAcAAAAVAIAAB4Abwlwcm9kdWNlcnMCCGxhbmd1YWdlAQRSdXN0AAxwcm9jZXNzZWQtYnkDBXJ1c3RjHTEuNzQuMSAoYTI4MDc3YjI4IDIwMjMtMTItMDQpBndhbHJ1cwYwLjIzLjIMd2FzbS1iaW5kZ2VuBjAuMi44OQAsD3RhcmdldF9mZWF0dXJlcwIrD211dGFibGUtZ2xvYmFscysIc2lnbi1leHQ=";
//                     if (typeof Buffer === 'undefined') {
//                         bytes = Uint8Array.from(atob(base64), c => c.charCodeAt(0));
//                     } else {
//                         bytes = Buffer.from(base64, 'base64');
//                     }
                    
//             export const booted = 
//             WebAssembly.instantiate(bytes,{  })
//                 .then(obj => {
//                     const wasm = obj.instance;
//                     memory = wasm.exports.memory;
// sign = wasm.exports.sign;
// __wbindgen_add_to_stack_pointer = wasm.exports.__wbindgen_add_to_stack_pointer;
// __wbindgen_malloc = wasm.exports.__wbindgen_malloc;
// __wbindgen_realloc = wasm.exports.__wbindgen_realloc;
// __wbindgen_free = wasm.exports.__wbindgen_free;

//                 })
//             ;
//             export let memory;
// export let sign;
// export let __wbindgen_add_to_stack_pointer;
// export let __wbindgen_malloc;
// export let __wbindgen_realloc;
// export let __wbindgen_free;

if (typeof Buffer === 'undefined') {
    bytes = Uint8Array.from(atob(base64), c => c.charCodeAt(0));
} else {
    bytes = Buffer.from(base64, 'base64');
}

// Variables to hold WASM exports, will be populated by the booted promise
let wasm;
let signWrapper; // The JS wrapper function we will export

export const booted =
    WebAssembly.instantiate(bytes, { /* imports object if needed */ })
        .then(obj => {
            wasm = obj.instance.exports; // Assign exports to wasm variable

            // --- Start: Helper functions and caches copied from sign.mjs ---
            let WASM_VECTOR_LEN = 0;
            let cachedUint8Memory0 = null;

            function getUint8Memory0() {
                if (cachedUint8Memory0 === null || cachedUint8Memory0.byteLength === 0) {
                    cachedUint8Memory0 = new Uint8Array(wasm.memory.buffer);
                }
                return cachedUint8Memory0;
            }

            const cachedTextEncoder =
                typeof TextEncoder !== 'undefined' ?
                    new TextEncoder('utf-8') : {
                        encode: () => {
                            throw Error('TextEncoder not available');
                        },
                    };

            const encodeString =
                typeof cachedTextEncoder.encodeInto === 'function' ?
                    function (arg, view) {
                        return cachedTextEncoder.encodeInto(arg, view);
                    } :
                    function (arg, view) {
                        const buf = cachedTextEncoder.encode(arg);
                        view.set(buf);
                        return {
                            read: arg.length,
                            written: buf.length,
                        };
                    };

            function passStringToWasm0(arg, malloc, realloc) {
                if (realloc === undefined) {
                    const buf = cachedTextEncoder.encode(arg);
                    const ptr = malloc(buf.length, 1) >>> 0;
                    getUint8Memory0()
                        .subarray(ptr, ptr + buf.length)
                        .set(buf);
                    WASM_VECTOR_LEN = buf.length;
                    return ptr;
                }

                let len = arg.length;
                let ptr = malloc(len, 1) >>> 0;

                const mem = getUint8Memory0();

                let offset = 0;

                for (; offset < len; offset++) {
                    const code = arg.charCodeAt(offset);
                    if (code > 0x7f) break;
                    mem[ptr + offset] = code;
                }

                if (offset !== len) {
                    if (offset !== 0) {
                        arg = arg.slice(offset);
                    }
                    ptr = realloc(ptr, len, (len = offset + arg.length * 3), 1) >>> 0;
                    const view = getUint8Memory0().subarray(ptr + offset, ptr + len);
                    const ret = encodeString(arg, view);

                    offset += ret.written;
                }

                WASM_VECTOR_LEN = offset;
                return ptr;
            }

            let cachedInt32Memory0 = null;

            function getInt32Memory0() {
                if (cachedInt32Memory0 === null || cachedInt32Memory0.byteLength === 0) {
                    cachedInt32Memory0 = new Int32Array(wasm.memory.buffer);
                }
                return cachedInt32Memory0;
            }

            const cachedTextDecoder =
                typeof TextDecoder !== 'undefined' ?
                    new TextDecoder('utf-8', { ignoreBOM: true, fatal: true }) : {
                        decode: () => {
                            throw Error('TextDecoder not available');
                        },
                    };

            if (typeof TextDecoder !== 'undefined') {
                cachedTextDecoder.decode();
            }

            function getStringFromWasm0(ptr, len) {
                ptr = ptr >>> 0;
                return cachedTextDecoder.decode(getUint8Memory0().subarray(ptr, ptr + len));
            }
            // --- End: Helper functions and caches copied from sign.mjs ---

            // --- Define the JavaScript wrapper for the sign function ---
            signWrapper = (nonce, timestamp, device_id, query) => {
                if (!wasm) {
                    throw new Error("WASM module not initialized yet.");
                }
                let deferred5_0;
                let deferred5_1;
                try {
                    // Get necessary functions from wasm exports
                    const malloc = wasm.__wbindgen_malloc;
                    const realloc = wasm.__wbindgen_realloc;
                    // const free = wasm.__wbindgen_free;
                    const rawSign = wasm.sign; // The actual WASM function
                    const addToStackPointer = wasm.__wbindgen_add_to_stack_pointer;

                    const retptr = addToStackPointer(-16);

                    const ptr0 = passStringToWasm0(nonce, malloc, realloc);
                    const len0 = WASM_VECTOR_LEN;

                    const ptr1 = passStringToWasm0(timestamp, malloc, realloc);
                    const len1 = WASM_VECTOR_LEN;

                    const ptr2 = passStringToWasm0(device_id, malloc, realloc);
                    const len2 = WASM_VECTOR_LEN;

                    const ptr3 = passStringToWasm0(query, malloc, realloc);
                    const len3 = WASM_VECTOR_LEN;

                    // Call the raw WASM sign function with pointers and lengths
                    rawSign(retptr, ptr0, len0, ptr1, len1, ptr2, len2, ptr3, len3);

                    var r0 = getInt32Memory0()[retptr / 4 + 0];
                    var r1 = getInt32Memory0()[retptr / 4 + 1];

                    // Store values to free later
                    deferred5_0 = r0;
                    deferred5_1 = r1;

                    // Decode the result string
                    return getStringFromWasm0(r0, r1);
                } finally {
                    // Clean up stack and free memory
                    if (wasm && wasm.__wbindgen_add_to_stack_pointer) {
                        wasm.__wbindgen_add_to_stack_pointer(16);
                    }
                    if (wasm && wasm.__wbindgen_free && deferred5_0 !== undefined) {
                        wasm.__wbindgen_free(deferred5_0, deferred5_1, 1);
                    }
                }
            };

            // Optional: Log success
            console.log("s.js: WASM instantiated and sign wrapper created.");
        })
        .catch(error => {
            console.error("s.js: Failed to instantiate WASM:", error);
            // Propagate the error so consumers of 'booted' know it failed
            throw error;
        });

// Export the signWrapper after the promise resolves and populates it
// We export a function that calls the wrapper, ensuring it exists first.
export function sign(nonce, timestamp, device_id, query) {
    if (!signWrapper) {
        throw new Error("sign function called before WASM initialization completed via booted promise.");
    }
    return signWrapper(nonce, timestamp, device_id, query);
}

// Note: We are no longer exporting memory, __wbindgen_malloc, etc., directly,
// as the wrapper handles their usage internally. Only 'booted' and the wrapped 'sign' are needed externally.
// If other raw WASM functions were needed externally, they'd need similar wrappers or direct export.